### ISSUE TITLE
An error when "python Build.py"

### ISSUE THREAD

**Issue by yangyufeng** [gongminmin/KlayGE#226] opened 2021-06-04 07:00 UTC
my python version 3.9.5 and CMake version 3.20.3

error:

Build information:
        CMake path: C:\Program Files (x86)\CMake\bin\cmake.exe
        CMake version: 320
        Host platform: win
        Target platform: win
        CPU count: 8
        Prefer static library: False
        Shader platform: auto
        Is dev platform: True
        Project type: vs2019
        Compiler: vc142
        Architectures: x64
        Configures: Debug, RelWithDebInfo
        GLES SDK include path: auto
        Oculus LibOVR path: auto

Building KlayGE...
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.8.5
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19042.
CMake Error at Modules/Common.cmake:12 (IF):
  if given arguments:

    "VERSION_LESS" "2.7.0"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:15 (include)

-- Configuring incomplete, errors occurred!
See also "D:/KlayGE/Build/vs2019_vc142_win_x64/CMakeFiles/CMakeOutput.log".
[W] Config KlayGE failed, retry 1...

How can I configuring complete?

**Comment by gongminmin** [comment] 2021-06-05 01:49
It has been fixed in https://github.com/gongminmin/KlayGE/commit/62d0a664ce2048aa7beac27a75483e9a05075ec1 in February. It's caused by a change in CMake.

**Closed as completed** 2021-06-05 01:49 UTC
Labels: bug, engineering
